# --- Physics & Lattice ---
omega0: 9831.0
a0: 3.5668194616854
Miller_h: 4
Miller_k: 0
Miller_l: 0

# --- Susceptibility (Branch 1) ---
delta1: 7.5628e-06
beta1: 7.32545e-09
xrh1: 0.372328E-05
xih1: 0.141150E-07

# --- Susceptibility (Branch 2) ---
delta2: 7.5628e-06
beta2: 7.32545e-09
xrh2: 0.372328E-05
xih2: 0.141150E-07

# --- Grid & Geometry ---
xgrid: 4000
ygrid: 1
res_x: 0
res_y: 0
xxmax: 2000
yymax: 10
asymm_angle: 90.0
thickness: 82
width: 0
d_film: 0
xs: 0
x00: -500
separation1: 0
separation2: 0
CrSize: 1000000
geometry: 'not_from_file'
geometry_file: 'Asymm.geom.npy'

# --- Numerical Integration ---
M: 4000
tpad: 4096
Zstep_factor: 0.05
method: 'Euler'
mode: 'TIDP'
zsep: 1

# --- Beam Properties ---
beam: 'Gaussian'
waist: 500
slit_x: 100000
slit_y: 100000
time_dependent: 'None'
tgrid: 0
tmax: 0
sigma_t: 0

# --- Deformation & Dislocations ---
deformation: 'None'
strain: 0
uz_filename: 'None'
x0d: 0
y0d: 0
z0d: 0
slope: 0
phid: 0
burgers_vector_x: 0
burgers_vector_screw: 0
v: 0
dudz: 0
depth: 0
B_size: 0
def_amplitude: 0
def_period: 4.0
def_B: 0

# --- Program Settings ---
nthread_fft: 4
quiet_mode: True
store_fields: True