# --- Physics & Lattice ---
omega0: 14400.0
a0: 3.5668194616854
Miller_h: 4
Miller_k: 4
Miller_l: 0
delta1: 3.520975e-06
beta1: 1.45485e-09
xrh1: 0.155388E-05
xih1: 0.270050E-08
delta2: 3.520975e-06
beta2: 1.45485e-09
xrh2: 0.155388E-05
xih2: 0.270050E-08

# --- Grid & Geometry ---
xgrid: 4000
ygrid: 1
res_x: 0
res_y: 0
xxmax: 100.0
yymax: 150.0
asymm_angle: 0
thickness: 20.0
width: 0.0
d_film: 0
xs: 0.0
x00: -50.0
separation1: 0
separation2: 0
CrSize: 800000
geometry: 'not_from_file'
geometry_file: 'Asymm.geom.npy'

# --- Numerical Integration ---
M: 2500
tpad: 512
Zstep_factor: 0.006666
method: 'Euler'
mode: 'TIDP'
zsep: 10

# --- Beam Properties ---
beam: 'Gaussian'
waist: 4000.0
slit_x: 10.0
slit_y: 100000.0
time_dependent: 'None'
tgrid: 0
tmax: 0.0
sigma_t: 0.0

# --- Deformation & Dislocations ---
deformation: 'Bent Spectrometer'
strain: 0
R: 0.095
vC100: 0.008
vC: 0.22
vSi: 0.22
def_B: 0.25
x0d: 0.0
y0d: -0.0
z0d: -0.0
slope: 0.0
phid: 1.5707963267948966
burgers_vector_x: 1.9200423982948915
burgers_vector_screw: 3.840084796589783
dudz: 0.0
depth: 0
B_size: 100
def_amplitude: 0.5e-10
def_period: 4.0

# --- Pump & Genesis (Settings) ---
# fname_GenV2: 'None'
# ncar_GenV2: 0
# dgrid_GenV2: 0.0
# mag_factor_GenV2: 1.0
# zsep_GenV2: 0
# crop_t: 1.0
# crop_x: 1.0
# uz_filename: 'None'

# --- Program Settings ---
nthread_fft: 4
quiet_mode: True
store_fields: True