# --- Physics & Lattice ---
omega0: 17450.0
a0: 5.4307
Miller_h: 2
Miller_k: 2
Miller_l: 0
delta1: 1.5904679835494718E-006
beta1: 8.1528117003473875E-009
xrh1: 1.921E-06
xih1: 1.55E-08
delta2: 1.5904679835494718E-006
beta2: 8.1528117003473875E-009
xrh2: 1.921E-06
xih2: 1.55E-08

# --- Grid & Geometry ---
xgrid: 400
ygrid: 400
res_x: 33333
res_y: 10
xxmax: 400.0
yymax: 100.0
asymm_angle: 90
thickness: 363.0
width: 0.0
d_film: 0
xs: 0.0
x00: 0.0
separation1: 0
separation2: 0
CrSize: 800
geometry: 'not_from_file'
geometry_file: 'Asymm.geom.npy'

# --- Numerical Integration ---
M: 400
tpad: 4096
Zstep_factor: 0.1
method: 'Verlet'
mode: 'TIDP'
zsep: 1

# --- Beam Properties ---
beam: 'Gaussian'
waist: 2000.0
slit_x: 10000.0
slit_y: 10000.0
time_dependent: 'None'
tgrid: 0
tmax: 0.0
sigma_t: 0.0

# --- Deformation & Dislocations ---
deformation: 'Dislocation_60degChukhovskiiConfiguration'
strain: 0
R: 0.0
vC100: 0.008
vC: 0.22
vSi: 0.22
def_B: 0.25
x0d: 10.0
y0d: 0.0
z0d: 0.0
slope: 0.0
phid: 0
burgers_vector_x: 1.9200423982948915
burgers_vector_screw: 3.840084796589783
dudz: 0.0
depth: 0
B_size: 0
def_amplitude: 0.5e-10
def_period: 4.0

# --- Pump & Genesis (Settings) ---
# fname_GenV2: 'None'
# ncar_GenV2: 0
# dgrid_GenV2: 0.0
# mag_factor_GenV2: 1.0
# zsep_GenV2: 0
# crop_t: 1.0
# crop_x: 1.0
# uz_filename: 'None'

# --- Program Settings ---
nthread_fft: 4
quiet_mode: True
store_fields: True