# --- Physics & Lattice ---
omega0: 17450.0
a0: 5.4307
Miller_h: 4
Miller_k: 4
Miller_l: 0
delta1: 1.5904679835494718E-006
beta1: 8.1528117003473875E-009
xrh1: 1.4034932345584149E-006
xih1: 1.5958203730559318E-008
delta2: 1.5904679835494718E-006
beta2: 8.1528117003473875E-009
xrh2: 1.4034932345584149E-006
xih2: 1.5958203730559318E-008

# --- Grid & Geometry ---
xgrid: 300
ygrid: 200
res_x: 33333
res_y: 10
xxmax: 15.0
yymax: 15.0
asymm_angle: 90
thickness: 10.0
width: 10.0
d_film: 0
xs: 0.0
x00: -5.0
separation1: 0
separation2: 0
CrSize: 10
geometry: 'from_file'
geometry_file: 'SiFiniteDisloc.geom.npy'

# --- Numerical Integration ---
M: 300
tpad: 4096
Zstep_factor: 0.005
method: 'Verlet'
mode: 'TIDP'
zsep: 50

# --- Beam Properties ---
beam: 'Gaussian'
waist: 4000.0
slit_x: 18.0
slit_y: 15.0
time_dependent: 'None'
tgrid: 0
tmax: 0.0
sigma_t: 0.0

# --- Deformation & Dislocations ---
deformation: 'Dislocation_60degGronkowskiConfiguration'
strain: 0
R: 0.0
vC100: 0.008
vC: 0.22
vSi: 0.22
def_B: 0.25
x0d: 0.0
y0d: -0.0
z0d: -0.0
slope: 0.0
phid: 1.5707963267948966
burgers_vector_x: 1.9200423982948915
burgers_vector_screw: 3.840084796589783
dudz: 0.0
depth: 0
B_size: 100
def_amplitude: 0.5e-10
def_period: 4.0

# --- Pump & Genesis (Settings) ---
# fname_GenV2: 'None'
# ncar_GenV2: 0
# dgrid_GenV2: 0.0
# mag_factor_GenV2: 1.0
# zsep_GenV2: 0
# crop_t: 1.0
# crop_x: 1.0
# uz_filename: 'None'

# --- Program Settings ---
nthread_fft: 1
quiet_mode: True
store_fields: True